### ISSUE TITLE
does not works with docker volume?

### ISSUE THREAD

**Issue by endyjasmi** [neutrinity/ntr-couch-docker#2]
When I try to use docker volume instead of the default host bind in the docker-compose. It complains about chown permission denied.

I am running this on Docker for Windows at windows 10 pro.

**Comment by cbsmith402** [comment]
I had the same problem, but I fixed it by going into Docker settings -> Shared Drives and then checking the C drive so that Docker could access it.

**Comment by lucidNTR** [comment]
@endyjasmi did @cbsmith402 s setting fix the issue or is it probable that the docker build/config is not correct?

**Comment by endyjasmi** [comment]
@lucidNTR sorry for the dangling issues. Yes, @cbsmith402 fix works for me.
